In [4]:
import pandas as pd

In [5]:
file_path = "../data/raw/betavanx_mvp_v1.xlsx"

In [6]:
xls = pd.ExcelFile(file_path)

xls.sheet_names

['Project', 'Task', 'Resource', 'DailyReport', 'ResourceUsage']

In [7]:
project_df = pd.read_excel(xls, sheet_name="Project")
task_df = pd.read_excel(xls, sheet_name="Task")
resource_df = pd.read_excel(xls, sheet_name="Resource")
daily_df = pd.read_excel(xls, sheet_name="DailyReport")
usage_df = pd.read_excel(xls, sheet_name="ResourceUsage")

In [10]:
merged_df = daily_df.merge(task_df, left_on="task_id", right_on="id")
merged_df.head()

,id_x,project_id_x,task_id,date,progress_percent,actual_cost,id_y,project_id_y,name,planned_duration,planned_cost
0,1,1,1,2026-01-01,10,50000,1,1,Excavation,5,300000
1,2,1,1,2026-01-02,25,120000,1,1,Excavation,5,300000
2,3,1,1,2026-01-03,40,200000,1,1,Excavation,5,300000
3,4,1,2,2026-01-06,10,100000,2,1,Foundation,10,800000
4,5,1,2,2026-01-07,20,250000,2,1,Foundation,10,800000

In [76]:
progress_summary = merged_df.groupby("task_id").agg({
    "progress_percent": "max",
    "actual_cost": "sum",
    "planned_cost": "first"
}).reset_index()
progress_summary

   task_id  progress_percent  actual_cost  planned_cost
0        1                40       370000        300000
1        2                20       350000        800000

In [77]:
progress_summary["expected_cost"] = (
    progress_summary["planned_cost"] * 
    (progress_summary["progress_percent"] / 100)
)

In [78]:
def check_status(row):
    expected_cost = row["planned_cost"] * (row["progress_percent"] / 100)

    if row["actual_cost"] > expected_cost:
        return "⚠️ Over Budget vs Progress"
    elif row["progress_percent"] == 100:
        return "✅ Completed"
    else:
        return "OK"
progress_summary["status"] = progress_summary.apply(check_status, axis=1)

In [79]:
progress_summary

,task_id,progress_percent,actual_cost,planned_cost,expected_cost,status
0,1,40,370000,300000,120000.0,⚠️ Over Budget vs Progress
1,2,20,350000,800000,160000.0,⚠️ Over Budget vs Progress

In [80]:
progress_summary

,task_id,progress_percent,actual_cost,planned_cost,expected_cost,status
0,1,40,370000,300000,120000.0,⚠️ Over Budget vs Progress
1,2,20,350000,800000,160000.0,⚠️ Over Budget vs Progress

In [83]:
progress_summary["cost_variance"] = (
    progress_summary["actual_cost"] - progress_summary["expected_cost"]
)
progress_summary["cost_variance_ratio"] = (
    progress_summary["cost_variance"] / progress_summary["expected_cost"]
)

progress_summary

,task_id,progress_percent,actual_cost,planned_cost,expected_cost,status,cost_variance,cost_variance_ratio
0,1,40,370000,300000,120000.0,⚠️ Over Budget vs Progress,250000.0,2.083333
1,2,20,350000,800000,160000.0,⚠️ Over Budget vs Progress,190000.0,1.187500

In [84]:
def calculate_score(row):
    ratio = row["cost_variance_ratio"]

    if pd.isna(ratio):
        return None
    
    if ratio <= 0:
        return 100  # خوب یا بهینه
    
    elif ratio <= 0.2:
        return 70   # کمی بد
    
    elif ratio <= 0.5:
        return 40   # بد
    
    else:
        return 10   # خیلی بد

In [85]:
progress_summary["score"] = progress_summary.apply(calculate_score, axis=1)

In [86]:
progress_summary

,task_id,progress_percent,actual_cost,planned_cost,expected_cost,status,cost_variance,cost_variance_ratio,score
0,1,40,370000,300000,120000.0,⚠️ Over Budget vs Progress,250000.0,2.083333,10
1,2,20,350000,800000,160000.0,⚠️ Over Budget vs Progress,190000.0,1.187500,10